"""updated sentiment analysis: added emotion scores

Revision ID: 61ca251855df
Revises: 
Create Date: 2026-05-09 23:11:27.378975

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61ca251855df'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'blogs', ['id'])
    op.add_column('sentiment', sa.Column('emotion_scores', sa.JSON(), nullable=True))
    op.create_unique_constraint(None, 'sentiment', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sentiment', type_='unique')
    op.drop_column('sentiment', 'emotion_scores')
    op.drop_constraint(None, 'blogs', type_='unique')
    # ### end Alembic commands ###
